import "~/styles/globals.css";
import { AuthKitProvider } from "@workos-inc/authkit-nextjs/components";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { PostHogProvider } from "./_providers/posthog-provider";

export const metadata: Metadata = {
  title: "Juan's Drive",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`dark ${geist.variable}`}>
      <body>
        <AuthKitProvider>
          <PostHogProvider>{children}</PostHogProvider>
        </AuthKitProvider>
      </body>
    </html>
  );
}
